avengers/urls.py
from django.urls import path

from . import views

app_name = 'avengers'


urlpatterns = [
    path('', views.index, name='index'),
    path('<avenger_name>', views.detail, name='detail'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('update/<int:id>', views.update, name='update'),
    # path('', views.create, name='create'),
]

sampleproject/urls.py
from django.contrib import admin
from django.urls import path

from sampleproject.views import root_page

from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', root_page),
    path('avengers/', include('avengers.urls'))
]

avengers/models.py
from django.db import models


class Avenger(models.Model):
    avenger_name = models.CharField(max_length=50)
    slug = models.SlugField(blank=True)

    add_date = models.DateTimeField(auto_now_add=True)

    referrals = models.IntegerField(default=0)

    def create(self):
        self.save()

    def __str__(self):
        return self.avenger_name

avengers/forms.py
from django import forms
from avengers.models import Avenger


class AvengerForm(forms.ModelForm):
    class Meta:
        model = Avenger
        fields = ('avenger_name',)

avengers/views.py
from .models import Avenger
from django.shortcuts import render, get_object_or_404, redirect
from .forms import AvengerForm


def index(request):

    # allows user to add to the roster without having to load a separate page
    if request.method == 'POST':
        form = AvengerForm(request.POST)

        if form.is_valid():
            avenger = form.save(commit=False)
            avenger.save()

            avenger_list = Avenger.objects.all()
            new_context = {
                'avenger_list': avenger_list,
            }

            return render(request, 'avengers/index.html', new_context)

    else:
        avenger_list = Avenger.objects.all()

        context = {
            'avenger_list': avenger_list,
        }
        return render(request, 'avengers/index.html', context)


def detail(request, avenger_name):

    avenger = get_object_or_404(Avenger, avenger_name=avenger_name)

    avenger.referrals += 1
    avenger.save()

    return render(request, 'avengers/detail.html', {'avenger': avenger})


def delete(request, id):
    avenger = get_object_or_404(Avenger, id=id)

    if request.method == 'POST':
        avenger.delete()

        return redirect('/avengers/')

    avenger_list = Avenger.objects.all()

    context = {
        'avenger_list': avenger_list,
    }
    return render(request, 'avengers/index.html', context)


def update(request, id):
    avenger = get_object_or_404(Avenger, id=id)
    if request.method == "POST":
        form = AvengerForm(request.POST, instance=avenger)
        if form.is_valid():
            avenger = form.save(commit=False)
            avenger.save()

            return redirect('/avengers/')
    else:
        return redirect('/avengers/')

sampleproject/views.py
from django.shortcuts import redirect

def root_page(request):
    return redirect('/avengers/')

avengers/templates/avengers/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'avengers/style.css' %}" />
<div class="content" id="details">

<h1 id="detailsHeader">{{ avenger.avenger_name }}</h1>
<p>Was added on {{ avenger.add_date }}</p>
<h2>{{ avenger.avenger_name }} has {{ avenger.referrals }} referrals!</h2>
<br>
<h3>Change {{ avenger.avenger_name }}'s name?</h3>
{% block content %}
<form method="POST" action="{% url 'avengers:update' avenger.id %}">
    {% csrf_token %}
    {{ form }}
  <input type="text" name="avenger_name">
    <input type="submit" value="Change Name" />
</form>
{% endblock %}

<a href="{% url 'avengers:index' %}">Back to the Bunker!</a>
</div>

avengers/templates/avengers/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'avengers/style.css' %}" />
<div class="content">
<h1>Welcome to the Avengers Bunker!</h1>
<br>

{% block content %}
<h4>Add New Avenger to the roster?</h4>
<form method="POST" action="{% url 'avengers:index' %}">
    {% csrf_token %}
    {{ form }}
  <input type="text" name="avenger_name">
    <input type="submit" value="Add" />
</form>
{% endblock %}


{% if avenger_list %}
<table id="avengers">
    <thead>
    <tr>
        <th>Avenger</th>
        <th>Clicks</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    </thead>
    <tbody>
    {% for avenger in avenger_list %}
    <tr>
        <td>{{ avenger.avenger_name }}</td>
        <td>{{ avenger.referrals }}</td>
        <td><a href="{% url 'avengers:detail' avenger.avenger_name %}">Edit</a></td>
        <td><form method="POST" action="{% url 'avengers:delete' avenger.id %}">{% csrf_token %}
            <input type="submit" value="Delete"></form></td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<p>No Avengers available. Thanos must have won. :(</p>
{% endif %}
</div>